title = "David Paul Weber"
description = "Personal portfolio and blog"
languageCode = "en-us"
baseurl = "https://dpweberza.github.io/davidpaulweber.com/"
categories = ["personal", "work", "projects"]
theme = "hyde"